services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: babyguestbook-front
        ports:
            - "3000:80"
        restart: unless-stopped
